// <auto-generated />
namespace Order_Management_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class order : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(order));
        
        string IMigrationMetadata.Id
        {
            get { return "202506270630165_order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
